language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.2.9
  - CAKE_VERSION=2.3.10
  - CAKE_VERSION=master
  - CAKE_VERSION=2.5

matrix:
  exclude:
    - php: 5.4
      env: CAKE_VERSION=2.2.9
    - php: 5.5
      env: CAKE_VERSION=2.2.9

before_script:
  - git clone --depth 1 git://github.com/cakephp/cakephp --branch $CAKE_VERSION ../cakephp && cd ../cakephp
  - git clone --depth 1 git://github.com/facebook/xhprof.git vendors/xhprof
  - sh -c "cd vendors/xhprof/extension && phpize && ./configure --enable-xhprof && make && sudo make install"
  - echo -ne "[xdebug]\nextension=xhprof.so\nxhprof.output_dir=/tmp" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo 'Configure::write("XHProf.library", dirname(APP) . "/vendors/xhprof/xhprof_lib");' >> app/Config/bootstrap.php
  - cp -R ../CakePHP-XHProf plugins/XHProf
  - mkdir -p build/logs
  - echo "<phpunit>
      <filter>
        <whitelist processUncoveredFilesFromWhitelist=\"true\">
          <directory suffix=\".php\">$(pwd)/plugins/XHProf</directory>
          <exclude>
            <directory suffix=\".php\">$(pwd)/plugins/XHProf/Test</directory>
          </exclude>
        </whitelist>
      </filter>
      <logging>
        <log type=\"coverage-clover\" target=\"build/logs/clover.xml\" />
      </logging>
    </phpunit>" > phpunit.xml
  - composer self-update
  - composer init --no-interaction
  - composer require --dev satooshi/php-coveralls:dev-master

script:
  - ./lib/Cake/Console/cake test XHProf AllXHProf

after_script:
  - ./vendor/bin/coveralls

notifications:
  email: false
